#!/usr/bin/env bash

set -e

mv ~/.vimrc ~/.vimrc.backup
ln -s $PWD/vim/.vimrc ~/.vimrc
mv ~/.vimrc.local ~/.vimrc.local.backup
ln -s $PWD/vim/.vimrc.local ~/.vimrc.local

mv ~/.tmux.conf ~/.tmux.conf.backup
ln -s $PWD/tmux/.tmux.conf ~/.tmux.conf

mv ~/.zshrc ~/.zshrc.backup
ln -s $PWD/zsh/.zshrc ~/.zshrc

mv ~/.zshrc.local ~/.zshrc.local.backup
ln -s $PWD/zsh/.zshrc.local ~/.zshrc.local

mv ~/.gitconfig ~/.gitconfig.backup
ln -s $PWD/git/.gitconfig ~/.gitconfig
mv ~/.gitconfig_personal ~/.gitconfig_personal.backup
ln -s $PWD/git/.gitconfig_personal ~/.gitconfig_personal
