#!/bin/bash

VIMPLUG_PATH="$HOME/.vim/autoload/plug.vim"
PREZTO_PATH="$HOME/.zprezto"
TPM_PATH="$HOME/.tmux/plugins/tpm"

if [[ `uname` == 'Darwin' ]]
then
	# Install Homebrew & Cask
	if [ ! hash git 2>/dev/null ]; then
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	else
		echo "HomeBrew is already installed!"
	fi

	brew tap caskroom/cask
	brew tap Homebrew/bundle
	brew bundle
else
	echo "brew not supports Linux, your need manual install dependentcies."
	echo "your install git, vim, tmux, zsh for the rest."
fi

# Install prezto
if [ ! -d "$PREZTO_PATH" ]; then
    git clone --recursive https://github.com/sorin-ionescu/prezto.git $PREZTO_PATH
else
    echo "ZSH Prezto is already installed!"
    cd $PREZTO_PATH && git pull && git submodule update --init --recursive
    cd -
fi

# Link dotfiles
./dotup


# Install Vim-plug
if [ ! -f "$VIMPLUG_PATH" ]; then
    curl -fLo $VIMPLUG_PATH --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
    echo "Vim Plug is already installed!"
fi
vim +PlugInstall +qall

# Install Tmux TPM
if [ ! -d "$TPM_PATH" ]; then
	git clone https://github.com/tmux-plugins/tpm $TPM_PATH
	$TPM_PATH/bin/install_plugins
else
    echo "Tmux TPM is already installed!"
fi

# Install tmuxitor
gem install tmuxinator
