#!/bin/bash

VIMPLUG_PATH="$HOME/.vim/autoload/plug.vim"
HOMEBREW="/usr/loca/Homebrew"

if [[ `uname` == 'Darwin' ]]
then
    # Install Homebrew & Cask
    if [ ! -f "$HOMEBREW" ]; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"
    else
        echo "HomeBrew is already installed!"
    fi

    brew tap Homebrew/bundle
    brew bundle
else
    echo "brew not supports Linux, your need manual install dependentcies."
    echo "your install git, vim, tmux, zsh for the rest."
fi

# Link dotfiles
./dotup


# Install Vim-plug
if [ ! -f "$VIMPLUG_PATH" ]; then
    curl -fLo $VIMPLUG_PATH --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
    echo "Vim Plug is already installed!"
fi
vim +PlugInstall +qall

# Install Asdf
sh asdf/add_plugins.sh
asdf install

# Install fzf
$(brew --prefix)/opt/fzf/install
