#!/bin/bash

VIMPLUG_PATH="$HOME/.vim/autoload/plug.vim"
PREZTO_PATH="$HOME/.zprezto"

if [[ `uname` == 'Darwin' ]]
then
    # Install Homebrew & Cask
    if [ ! hash git 2>/dev/null ]; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"
    else
        echo "HomeBrew is already installed!"
    fi

    brew tap Homebrew/bundle
    brew bundle
else
    echo "brew not supports Linux, your need manual install dependentcies."
    echo "your install git, vim, tmux, zsh for the rest."
fi

# Install prezto
if [ ! -d "$PREZTO_PATH" ]; then
    git clone --recursive https://github.com/sorin-ionescu/prezto.git $PREZTO_PATH
else
    echo "ZSH Prezto is already installed!"
    cd $PREZTO_PATH && git pull && git submodule update --init --recursive
    cd -
fi

# Link dotfiles
./dotup


# Install Vim-plug
if [ ! -f "$VIMPLUG_PATH" ]; then
    curl -fLo $VIMPLUG_PATH --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
    echo "Vim Plug is already installed!"
fi
vim +PlugInstall +qall

# Install Asdf
sh asdf/add_plugins.sh
asdf install

# Install fzf
$(brew --prefix)/opt/fzf/install
